# Generated by Django 4.2 on 2025-10-16 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('agegroupid', models.IntegerField(primary_key=True, serialize=False)),
                ('agegroup', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'agegroup',
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('passwrd', models.CharField(max_length=25)),
                ('usertype', models.IntegerField()),
            ],
            options={
                'db_table': 'appuser',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('clusterid', models.IntegerField(primary_key=True, serialize=False)),
                ('clustername', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cluster',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('postid', models.IntegerField(primary_key=True, serialize=False)),
                ('postdate', models.DateField()),
                ('postlink', models.CharField(max_length=2048)),
                ('postmessage', models.CharField(max_length=2048)),
                ('clusterid', models.ForeignKey(db_column='clusterid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.cluster')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateid', models.IntegerField(primary_key=True, serialize=False)),
                ('statename', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'state',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('responseid', models.IntegerField(primary_key=True, serialize=False)),
                ('responsedate', models.DateField()),
                ('responsemessage', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others'), ('N', 'Not Disclosed')], default='NA', max_length=2)),
                ('sentiment', models.CharField(choices=[('P', 'Positive'), ('N', 'Negative'), ('U', 'Neutral')], max_length=1)),
                ('agegroupid', models.ForeignKey(db_column='agegroupid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.agegroup')),
                ('postid', models.ForeignKey(db_column='postid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.post')),
                ('stateid', models.ForeignKey(db_column='stateid', on_delete=django.db.models.deletion.CASCADE, to='dashboard.state')),
            ],
            options={
                'db_table': 'response',
            },
        ),
    ]
