# Generated by Django 4.2 on 2025-10-16 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={'managed': False},
        ),
    ]
